<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="JungHoons-MacBook-Pro.local" failures="1" tests="1" name="PositiveLoginTest" time="5.577" errors="0" timestamp="2024-07-09T00:13:34 CDT">
  <testcase classname="com.herokuapp.internet.loginTest.PositiveLoginTests" name="loginTest" time="2.667">
    <failure type="java.lang.AssertionError" message="expected [http://the-internet.herokuapp.com/secure] but found [https://the-internet.herokuapp.com/secure]">
      <![CDATA[java.lang.AssertionError: expected [http://the-internet.herokuapp.com/secure] but found [https://the-internet.herokuapp.com/secure]
at com.herokuapp.internet.loginTest.PositiveLoginTests.loginTest(PositiveLoginTests.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- PositiveLoginTest -->
